# Generated by Django 4.2 on 2023-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='address1',
            new_name='client_address1',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='address2',
            new_name='client_address2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='contact_person',
            new_name='client_contact_person',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='contact_reference',
            new_name='client_contact_reference',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='country',
            new_name='client_country',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='org_number',
            new_name='client_org_number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='place',
            new_name='client_place',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='zipcode',
            new_name='client_zipcode',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
